from typing import TypedDict, Annotated, List
import operator

class ResearchState(TypedDict):
    # The original user request
    query: str 
    
    # List of steps generated by the Planner
    plan: List[str] 
    
    # Accumulated research notes. 
    # The `Annotated[..., operator.add]` tells LangGraph that when an agent 
    # returns new research, it should APPEND to this list, not overwrite it.
    research_data: Annotated[List[str], operator.add] 
    
    # Track iterations to prevent infinite loops between Researcher and Reviewer
    revision_count: int 
    
    # Feedback from the Reviewer if the research is insufficient
    feedback: str 
    
    # The final synthesized markdown report
    final_report: str